---
tenant:
  name: test
  
  groups:
    - name: test_developer
      members:
        - tester
        - owner 
        - reporter
    - name: test_developer1
      members:
        - test
        - owner 
        - reporter
        - developer
        - mgalesloot
        - maintainer
    - name: test_developer2
      members:
        - test
        - owner 
        - reporter
        

  
